/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interface_graphique;

import application_pronostics.GestionExcel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.Timer;

/**
 *
 * @author Sofiane
 */
public class Master extends javax.swing.JFrame implements ActionListener{
       SimpleDateFormat sdf = new SimpleDateFormat ( "HH: mm : ss "); 
    /**
     * Creates new form Master
     */
    public Master() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MASTER");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Domicile", "Extérieur"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Save Matchs et Classement");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deconnexion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Ouvrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Prénom", "Points"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton5.setText("Ouvrir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Retour");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(sdf.format ( new Date ( System.currentTimeMillis ( ))) );
        Timer timer = new Timer (500, this);
        timer.setRepeats (true);
        timer.start ();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton5)
                        .addGap(136, 136, 136)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // recup des matchs et sauvegarde 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String[] match = new String[20+GestionExcel.NOMBRE_DE_JOUEUR*2];
        String[] classement = new String[GestionExcel.NOMBRE_DE_JOUEUR*2];
        GestionExcel test = new GestionExcel();
        int k = 0; 
        int s; 
        
        // Remplissage du tableau de matchs
        
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 2; j++) {
                match[k] = jTable1.getValueAt(i, j).toString(); 
                
                   if(jTable1.getValueAt(i, j)==null){
                   JOptionPane.showMessageDialog(null, "Veuillez remplir toutes les cases", "Attention",WARNING_MESSAGE); 
                }
                k++;
            }
        }
        
        // Remplissage du tableau de classement
        k=0;
        for (int i = 0; i <GestionExcel.NOMBRE_DE_JOUEUR; i++) {
            for (int j = 0; j < 2; j++) {
                classement[k] = jTable2.getValueAt(i, j).toString(); 
                
                   if(jTable2.getValueAt(i, j)==null){
                   JOptionPane.showMessageDialog(null, "Veuillez ouvrir le classement avant", "Attention",WARNING_MESSAGE); 
                }
                k++;
            }
        }
        
        for(int i = 0; i<(GestionExcel.NOMBRE_DE_JOUEUR*2); i++){
            match[20+i] = classement[i];
            }
        
        String path = "Match_sauvegarde.csv";
        s=test.saveAs(match,path);
        
        if(s==1){
        JOptionPane.showMessageDialog(null, "sauvegarde réussie", "Information",INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       JFrame j = new Identification();
       j.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    // Les pronostics des joueurs ! 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int nombreDePronostic = 1;
        int tailleTableau = 40 * GestionExcel.NOMBRE_DE_JOUEUR;
        pronosticsJoueurs = new String[tailleTableau];
        String pronosticPath;
        GestionExcel excel = new GestionExcel();
        
        pronosticPath = excel.open();
        pronosticsJoueursTemp = excel.lireProno(pronosticPath,nombreDePronostic);
        
        int j;
        
        for(int i = 0; i < 40; i++){
           j= i + i*nbreDeFichier;
            pronosticsJoueurs[j] = pronosticsJoueursTemp[i];
        }
        
        nbreDeFichier++;  
        
        String pronosticPathSave = "Vos_Pronostics.csv";
        int s;
        s = excel.saveAs(pronosticsJoueurs, pronosticPathSave);
        
        if (s == 1) {
            JOptionPane.showMessageDialog(null, "sauvegarde réussie", "Information", INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // Bouton ouvrir classement
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        GestionExcel excel = new GestionExcel();
        String classementPath;
        String[] classementTab;
        classementPath = excel.open();
        System.out.println("Fichier ouvert : " + classementPath);
        
        
        classementTab = excel.lireClassement(classementPath);
        int k=0;
        for(int i = 0; i<GestionExcel.NOMBRE_DE_JOUEUR; i++){
            for(int j=0; j<2; j++){
                jTable2.setValueAt(classementTab[k], i, j);
                k++;
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            JFrame j = new Sommaire();
            j.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    private int nbreDeFichier = 0;
    String[] pronosticsJoueursTemp = new String[40];
    String[] pronosticsJoueurs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
          jLabel5.setText(sdf.format(new Date(System.currentTimeMillis())));  
    }
}
