/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_graphique;

import application_pronostics.BaseDeDonnee;
import application_pronostics.GestionExcel;
import application_pronostics.Joueur;
import application_pronostics.LectureXML;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Sofiane
 */
public class Pronostic extends javax.swing.JFrame implements ActionListener {

    private LectureXML test = new LectureXML("donnees.xml");
    private BaseDeDonnee bdJ = test.getJ();
    private String password;
    SimpleDateFormat sdf = new SimpleDateFormat ( "HH: mm : ss ");

    /**
     * Creates new form Pronostic
     */
    public Pronostic(String password) {
        this.password = password;
        initComponents();
        if (!(password.equals("master"))) {
            jPanel2.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText(sdf.format ( new Date ( System.currentTimeMillis ( ))) );
        Timer timer = new Timer (500, this);
        timer.setRepeats (true);
        timer.start ();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pronostic");

        jScrollPane3.setBorder(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Domicile", "", "", "Extérieur"
            }
        ));
        jTable3.setEnabled(false);
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane2.addTab("Amar", jScrollPane3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Domicile", "", "", "Extérieur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setEnabled(false);
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
            jTable4.getColumnModel().getColumn(2).setResizable(false);
            jTable4.getColumnModel().getColumn(3).setResizable(false);
        }

        jTabbedPane2.addTab("Enis", jScrollPane4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Domicile", "", "", "Extérieur"
            }
        ));
        jTable5.setEnabled(false);
        jScrollPane5.setViewportView(jTable5);

        jTabbedPane2.addTab("Farid", jScrollPane5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Domicile", "", "", "Extérieur"
            }
        ));
        jTable6.setEnabled(false);
        jScrollPane6.setViewportView(jTable6);

        jTabbedPane2.addTab("Lyes", jScrollPane6);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Domicile", "", "", "Extérieur"
            }
        ));
        jTable7.setEnabled(false);
        jScrollPane7.setViewportView(jTable7);

        jTabbedPane2.addTab("Salim", jScrollPane7);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Domicile", "", "", "Extérieur"
            }
        ));
        jTable8.setEnabled(false);
        jScrollPane8.setViewportView(jTable8);

        jTabbedPane2.addTab("Sofiane", jScrollPane8);

        jScrollPane9.setBorder(null);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Domicile", "", "", "Extérieur"
            }
        ));
        jTable9.setEnabled(false);
        jScrollPane9.setViewportView(jTable9);

        jTabbedPane2.addTab("Youcef", jScrollPane9);

        jTabbedPane1.addTab("Pronostic", jTabbedPane2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Domicile", "", "", "Exterieur", "1", "N", "P"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setMinimumSize(new java.awt.Dimension(100, 200));
        jTable1.setPreferredSize(new java.awt.Dimension(100, 200));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jTabbedPane1.addTab("Résultat de la journée", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Points"
            }
        ));
        jTable2.setEnabled(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        jTabbedPane1.addTab("Classement Actualisé", jScrollPane2);

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Deconnexion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualisation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ouvrir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Save classement");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(sdf.format ( new Date ( System.currentTimeMillis ( ))) );
        Timer timer1 = new Timer (500, this);
        timer1.setRepeats (true);
        timer1.start ();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Résultat de la journée");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (password.equals("master")) {
            JFrame j = new Sommaire();
            j.setVisible(true);
            this.dispose();
        } else {
            JFrame j = new Accueil(password);
            j.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFrame j = new Identification();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        /**
         * ** recupere le fichier de pronstic ***
         */
        GestionExcel excel = new GestionExcel();
        int tailleFichierPronostic;
        tailleFichierPronostic = 40 * GestionExcel.NOMBRE_DE_JOUEUR + 2 * GestionExcel.NOMBRE_DE_JOUEUR;;

        pronostic = new String[tailleFichierPronostic];
        String pronosticPath;
        pronosticPath = excel.open();
        System.out.println("Fichier ouvert : " + pronosticPath);

        // lecture du fichier de pronostics et copie dans le tableau pronostic
        //pronostic = excel.lireProno(pronosticPath, GestionExcel.NOMBRE_DE_JOUEUR);
        pronostic = excel.lireMatchsEtClassement(pronosticPath);

        /**
         * ** procede à l'affichage des matchs ***
         */
        int k = 0;
        int l = 3;
        for (int i = 0; i < 10; i++) {

            jTable1.setValueAt(pronostic[k], i, 0);
            jTable1.setValueAt(pronostic[l], i, 3);
            k = k + 4;
            l = l + 4;
        }

        /**
         *** procede à l'affichage des pronostics ***
         */
        k = 0;

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 4; j++) {
                jTable3.setValueAt(pronostic[k], i, j);  // renplissage table Amar
                jTable4.setValueAt(pronostic[40 + k], i, j);  // renplissage table Enis
                jTable5.setValueAt(pronostic[80 + k], i, j);  // renplissage table Farid
                jTable6.setValueAt(pronostic[120 + k], i, j);  // renplissage table Lyes
                jTable7.setValueAt(pronostic[160 + k], i, j);  // renplissage table Salim
                jTable8.setValueAt(pronostic[200 + k], i, j);  // renplissage table Sofiane
                jTable9.setValueAt(pronostic[240 + k], i, j);  // renplissage table Youcef

                k++;
            }
        }

        k = 0;
        /**
         *** procede à l'affichage du classement ***
         */
        for (int i = 0; i < GestionExcel.NOMBRE_DE_JOUEUR; i++) {
            for (int j = 0; j < 2; j++) {
                jTable2.setValueAt(pronostic[k + 280], i, j);  // renplissage table Amar

                k++;
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    // actualisation 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String[] pronoAmar = new String[40];
        String[] pronoEnis = new String[40];
        String[] pronoLyes = new String[40];
        String[] pronoFarid = new String[40];
        String[] pronoSalim = new String[40];
        String[] pronoSofiane = new String[40];
        String[] pronoYoucef = new String[40];

        int l = 0;

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 4; j++) {

                pronoAmar[l] = jTable3.getValueAt(i, j).toString();  // remplissage du tableau Amar
                pronoEnis[l] = jTable4.getValueAt(i, j).toString();  // remplissage du tableau Enis
                pronoFarid[l] = jTable5.getValueAt(i, j).toString();  // remplissage du tableau Farid
                pronoLyes[l] = jTable6.getValueAt(i, j).toString();  // remplissage du tableau Lyes
                pronoSalim[l] = jTable7.getValueAt(i, j).toString();  // remplissage du tableau Salim
                pronoSofiane[l] = jTable8.getValueAt(i, j).toString();  // remplissage du tableau Sofiane
                pronoYoucef[l] = jTable9.getValueAt(i, j).toString();  // remplissage du tableau Youcef

                l++;
            }
        }

        GestionExcel excel = new GestionExcel();
        resultats = new String[40];
        int k = 0;

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 4; j++) {
                resultats[k] = jTable1.getValueAt(i, j).toString();  // remplissage table Resultats

                k++;
            }
        }

        Joueur Amar = null;
        Joueur Enis = null;
        Joueur Farid = null;
        Joueur Lyes = null;
        Joueur Salim = null;
        Joueur Sofiane = null;
        Joueur Youcef = null;

        int AmarP = excel.calculPoints(pronoAmar, resultats) + Integer.parseInt(pronostic[280 + 1]);
        int EnisP = excel.calculPoints(pronoEnis, resultats) + Integer.parseInt(pronostic[280 + 3]);
        int FaridP = excel.calculPoints(pronoFarid, resultats) + Integer.parseInt(pronostic[280 + 5]);
        int LyesP = excel.calculPoints(pronoLyes, resultats) + Integer.parseInt(pronostic[280 + 7]);
        int SalimP = excel.calculPoints(pronoSalim, resultats) + Integer.parseInt(pronostic[280 + 9]);
        int SofianeP = excel.calculPoints(pronoSofiane, resultats) + Integer.parseInt(pronostic[280 + 11]);
        int YoucefP = excel.calculPoints(pronoYoucef, resultats) + Integer.parseInt(pronostic[280 + 13]);

        jTable2.setValueAt("Amar", 0, 0);
        jTable2.setValueAt(AmarP, 0, 1);

        jTable2.setValueAt("Enis", 1, 0);
        jTable2.setValueAt(EnisP, 1, 1);

        jTable2.setValueAt("Farid", 2, 0);
        jTable2.setValueAt(FaridP, 2, 1);

        jTable2.setValueAt("Lyes", 3, 0);
        jTable2.setValueAt(LyesP, 3, 1);

        jTable2.setValueAt("Salim", 4, 0);
        jTable2.setValueAt(SalimP, 4, 1);

        jTable2.setValueAt("Sofiane", 5, 0);
        jTable2.setValueAt(SofianeP, 5, 1);

        jTable2.setValueAt("Youcef", 6, 0);
        jTable2.setValueAt(YoucefP, 6, 1);
        
        jTable2.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    // sauvegarde du classement 
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       // TODO add your handling code here:

        String[] classement = new String[14];
        int l = 0;
        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 2; j++) {

                classement[l] = jTable2.getValueAt(i, j).toString();  // remplissage du classement

                l++;
            }
        }
        String classementPath = "classement.csv";
        GestionExcel excel = new GestionExcel();
        excel.saveAs(classement, classementPath);


    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    private String[] pronostic;
    private String[] resultats;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
         jLabel7.setText(sdf.format(new Date(System.currentTimeMillis())));  
    }
}
